version: '3.8'
services:
  node:
    build:
      context: .
    ports:
      - '3001:3000'
    environment:
      - MONGO_DB_USERNAME=myuser
      - MONGO_DB_PWD=mypassword
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myuser
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
  mongo-express:
    image: mongo-express:latest
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=myuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mypassword
      - ME_CONFIG_BASICAUTH_USERNAME=newadmin # New username
      - ME_CONFIG_BASICAUTH_PASSWORD=newpass # New password
    depends_on:
      - mongodb
